// <auto-generated />
using System;
using Methanit_ASP_NET_Core_7;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FridgeProducts.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230131094005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Methanit_ASP_NET_Core_7.Models.Fridge", b =>
                {
                    b.Property<Guid>("FridgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Fridge_ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Owner_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("FridgeId");

                    b.HasIndex("Fridge_ModelId");

                    b.ToTable("Fridges");
                });

            modelBuilder.Entity("Methanit_ASP_NET_Core_7.Models.Fridge_Model", b =>
                {
                    b.Property<Guid>("Fridge_ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Fridge_ModelId");

                    b.ToTable("Fridge_Models");
                });

            modelBuilder.Entity("Methanit_ASP_NET_Core_7.Models.Fridge_Products", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FridgeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridgeId");

                    b.HasIndex("ProductId");

                    b.ToTable("FridgeProducts");
                });

            modelBuilder.Entity("Methanit_ASP_NET_Core_7.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Default_Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Methanit_ASP_NET_Core_7.Models.Fridge", b =>
                {
                    b.HasOne("Methanit_ASP_NET_Core_7.Models.Fridge_Model", "Fridge_Model")
                        .WithMany("Fridges")
                        .HasForeignKey("Fridge_ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridge_Model");
                });

            modelBuilder.Entity("Methanit_ASP_NET_Core_7.Models.Fridge_Products", b =>
                {
                    b.HasOne("Methanit_ASP_NET_Core_7.Models.Fridge", "Fridges")
                        .WithMany("Fridge_Products")
                        .HasForeignKey("FridgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Methanit_ASP_NET_Core_7.Models.Product", "Products")
                        .WithMany("Fridge_Products")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fridges");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Methanit_ASP_NET_Core_7.Models.Fridge", b =>
                {
                    b.Navigation("Fridge_Products");
                });

            modelBuilder.Entity("Methanit_ASP_NET_Core_7.Models.Fridge_Model", b =>
                {
                    b.Navigation("Fridges");
                });

            modelBuilder.Entity("Methanit_ASP_NET_Core_7.Models.Product", b =>
                {
                    b.Navigation("Fridge_Products");
                });
#pragma warning restore 612, 618
        }
    }
}
